### ISSUE TITLE
确认INCOMPATIBLE protocol 的意思

### ISSUE THREAD

**Issue by erutique** [mrluanma/shadowsocks-heroku#10]
我是否可以理解成，除了```node local.js -s  ###########```以外，
现有的其他shadowsocks client on android/ios/win/linux 均无法连接？

话说，这让我想起了JAP (https://code.google.com/p/jap/)

**Comment by mrluanma** [comment]
是的。这个是 shadowsocks over WebSocket。

不了解 JAP。

**Comment by mrluanma** [comment]
这里有将原生 shadowsocks 的 TCP socket WebSocket-ify 之后跑在 Heroku 上的 Hack：

https://github.com/mrluanma/shadowsocks-websocket-python

0 行代码实现了 mrluanma/shadowsocks-heroku 这里的服务端部分，和这里使用的是同样的协议，可以搭配这里的 node local.js 来使用。

**Comment by erutique** [comment]
THX!
