### ISSUE TITLE
heroku   Error: read ETIMEDOUT

### ISSUE THREAD

**Issue by JoeWoo** [mrluanma/shadowsocks-heroku#11]
@mrluanma  heroku ws 协议。我遇到的error是超时。更新了代码问题还是复现。

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ETIMEDOUT
    at errnoException (net.js:905:11)
    at TCP.onread (net.js:559:19)
```

下面link给你参考：
http://stackoverflow.com/questions/14972106/how-to-deal-with-read-etimedout-in-node-js

**Comment by mrluanma** [comment]
I have run the latest code for a while, and it is relatively stable.
