### ISSUE TITLE
npm install 出错，缺少Visual Studio 2008？？

### ISSUE THREAD

**Issue by suoba** [mrluanma/shadowsocks-heroku#16]
$ npm install
npm WARN package.json shadowsocks-heroku@0.9.9 No repository field.
\

> ws@0.6.5 install d:\shadowsocks\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

d:\shadowsocks\node_modules\ws>if not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\n
pm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not instal
led, either 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install
 Microsoft Visual Studio 2008.  [d:\shadowsocks\node_modules\ws\build\binding.sln]
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not instal
$
 Microsoft Visual Studio 2008.  [d:\shadowsocks\node_modules\ws\build\binding.sln]
minimist@1.1.1 node_modules\minimist

ws@0.6.5 node_modules\ws
├── options@0.0.6
├── ultron@1.0.1
└── nan@1.4.3

**Comment by louy2** [comment]
ws 需要 VS 来编译的，只要安装 VS2008 及以后任意版本的免费版（Express）就可以了。
