### ISSUE TITLE
mrluanma, can you please add the support for android client? 

### ISSUE THREAD

**Issue by kang000feng** [mrluanma/shadowsocks-heroku#17]
First of all, your app is  really awesome. thanks very much.
secondly, is there any way to add the support for android client? can you try it out? that will be perfect. i assume a lot of people would like to see it happen here. thank you for your innovation.

**Comment by LightMoon** [comment]
Yes I am one of those people who waiting for any creative solutions.
Any idea guys ?

**Comment by mrluanma** [comment]
It's not within the consideration of this project.
