### ISSUE TITLE
openshift打不开https开头的网址

### ISSUE THREAD

**Issue by ren2014311** [mrluanma/shadowsocks-heroku#19]
在openshift部署好了，但是打不开https的网址，http的却没有问题，这个情况怎么解决啊？

**Comment by mrluanma** [comment]
听起来是浏览器没有将 HTTPS 的请求通过代理转发。

**Comment by ren2014311** [comment]
但是heroku部署的就没有这种情况，，

**Comment by david-stratusee** [comment]
这个有解吗？我的也是这样的情况。开发者是否还在？我通过curl测试的，确实是进代理了，但连接不上。

**Comment by david-stratusee** [comment]
connection.on("data", function(data) {
      var addrtype, buf, cmd, e, reply, tempBuf;

      //console.log("[1]get " + data.length + " data from local" + ", stage: " + stage);

      if (stage === 5) {
        data = encryptor.encrypt(data);
        if (ws.readyState === WebSocket.OPEN) {
          //console.log("[2]send " + data.length + " data to server, get bufferedAmount: " + ws.bufferedAmount + ", stage: " + stage);
          ws.send(data, {
            binary: true
          }); 
          //if (ws.bufferedAmount > 0) {
            //console.log("[23]pause local, get bufferedAmount: " + ws.bufferedAmount);
            //connection.pause();
          //}
        }   
        return;
      } 
我把这里的connection.pause和后面的connection.resume()给去掉了，就好了

**Comment by mrluanma** [comment]
@david-stratusee 可以整理一下发一个 PR 给我，请修改 .coffee 文件。
