### ISSUE TITLE
客户端有时崩溃

### ISSUE THREAD

**Issue by catdog** [mrluanma/shadowsocks-heroku#25]
出错信息:

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:855:11)
    at TCP.onread (net.js:544:26)

**Comment by windmaple** [comment]
Had the same issue. I ended up using a bash loop to restart the client once it crashes. Hopefully it gets fixed.

connecting www.youtube.com via ws://shadowsocks-heroku-windmaple.herokuapp.com:80/
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ETIMEDOUT
    at exports._errnoException (util.js:896:11)
    at TCP.onread (net.js:556:26)

**Comment by mrluanma** [comment]
I have run the latest code for a while, and it is relatively stable.
