### ISSUE TITLE
关于连接复用的想法

### ISSUE THREAD

**Issue by bdbai** [mrluanma/shadowsocks-heroku#28]
您好，我在国际版 Azure 网站平台上部署了这个项目，现在基本可以用了。但是，免费版的 Azure 计划限制 WebSocket 连接数仅为 5 个，而加载一个网页通常需要建立数十个连接，体验并不好。请问能否把这些连接合并为一个来减少总的连接数？谢谢！

**Comment by bigbagboom** [comment]
我觉得不太可能。看一下原来的代码，连接实际上是由客户端（也就是浏览器或其他需要访问网络的程序）发起的，作为代理只能对每一个发起的连接生成一个对应的线程，让这些线程共享websocket同时保证其应答同步需要很精巧或复杂的设计，想想就头疼了.......

**Comment by milkice233** [comment]
@bdbai 问一下怎么在azure上搭建的...一直没能成功

**Comment by bdbai** [comment]
@milkice233 抱歉我不太记得了...
IIS+Node 那一套比较恶心，当时我改了好多配置文件，好像是允许某种请求才可以的。
