### ISSUE TITLE
配置成功后android端无法连接成功

### ISSUE THREAD

**Issue by HanSon** [mrluanma/shadowsocks-heroku#31]
电脑上可以成功翻墙，android端按照参数配置 域名 远程端口80 本地1080 密码 & 加密方式，但无法链接成功，求解

**Comment by mrluanma** [comment]
README 里有说明：并不兼容 shadowsocks 协议。

> Notice that the protocol is INCOMPATIBLE with the origin shadowsocks.

**Comment by W-quan** [comment]
只能在电脑上使用吗？
