### ISSUE TITLE
Is it possible to change remote-port ?

### ISSUE THREAD

**Issue by LightMoon** [mrluanma/shadowsocks-heroku#32]
Hi,

Is it possible to change remote-port from 80 to anything else ?
For example, 443 or 8080

Thanks

**Comment by mrluanma** [comment]
Yes.

**Comment by LightMoon** [comment]
The problem is that when I change the port number to 443 or 8080 is not working.
I tried these ports on Heroku.

**Comment by mrluanma** [comment]
shadowsocks-heroku is running behind the Heroku proxy, you need to figure out how Heroku do [HTTP Routing](https://devcenter.heroku.com/articles/http-routing).

Heroku only accept requests on 80(HTTP), 443(HTTPS) ports, if you want to use 443 port, try this:

```
node local.js -s wss://still-tor-8707.herokuapp.com:443 -l 1080 -m rc4 -k foobar
```
