### ISSUE TITLE
address in using,aborting

### ISSUE THREAD

**Issue by 15331094** [mrluanma/shadowsocks-heroku#33]
启动本地 client后cmd上显示address in using,aborting，请问这是什么错误？

**Comment by mrluanma** [comment]
local.js 需要绑定的端口号（默认配置文件 config.json 里的 local_port 和 README.md 里的命令行参数 -l 均为 1080）被其它程序占用，更换成其它端口（比如 1089）即可。

**Comment by 15331094** [comment]
是的，后来我改成1090解决这个问题了，谢谢！
