### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by aih8** [mrluanma/shadowsocks-heroku#35]
my item show something like this:
concurrent connections: 1
remote github.com:443 error: Error: connect ECONNREFUSED 23.23.117.76:8080
remote disconnected
concurrent connections: 0
local connected
concurrent connections: 1
remote github.com:443 error: Error: connect ECONNREFUSED 23.23.117.76:8080
remote disconnected
concurrent connections: 0

**Comment by zihengfox** [comment]
i want to know how to fix this, thanks

**Comment by onplus** [comment]
https://github.com/onplus/shadowsocks-heroku/issues/1
