### ISSUE TITLE
How to use a reversed proxy like nginx or haproxy to proxy multiple socks5 proxy?

### ISSUE THREAD

**Issue by minibear0523** [mrluanma/shadowsocks-heroku#38]
I have deploy 50 heroku apps on a single server, which uses as many as 50 ports on the server. When I crawl some website, I should random choose ip: ports on the server. But I wanna  use a reverse proxy to make a load balance with one ip:port.

I have search on the google that nginx doesn't support socks protocol. So how can I archive this?

**Comment by onplus** [comment]
multiple forwarders
https://github.com/nadoo/glider

**Comment by mrluanma** [comment]
Out of scope of this little project.
