### ISSUE TITLE
works on firefox but not chrome

### ISSUE THREAD

**Issue by kc1** [mrluanma/shadowsocks-heroku#41]
I'm working on win10 64 bit

my config.json:

{
  "server": "127.0.0.1",
  "local_address": "127.0.0.1",
  "scheme": "ws",
  "local_port": 1337,
  "remote_port": 80,
  "password": "`try*(^^$some^$%^complex>:<>?~password/",
  "timeout": 600,
  "method": "rc4-md5"
}

command line:

$ node local.js -s myapp.herokuapp.com -l 1337 -m rc4 -k mykey-r 80

firefox 57 - works:

![capture1](https://user-images.githubusercontent.com/1745710/34590775-d7488e7c-f186-11e7-9cb3-113a12f9d172.PNG)

chrome 63 --  does not work
![capture](https://user-images.githubusercontent.com/1745710/34590677-5333f6c6-f186-11e7-859f-015de09aaf28.PNG)

How can I get chrome working?

**Comment by mrluanma** [comment]
https://github.com/FelisCatus/SwitchyOmega/releases/tag/v2.5.9

**Comment by kc1** [comment]
Thank you
