### ISSUE TITLE
openshift 无法使用

### ISSUE THREAD

**Issue by instafun** [mrluanma/shadowsocks-heroku#6]
部署到openshift后，连接到各网站都会出现类似的error:
remote www.youtube.com:443 error: server responded with an invalid protocol

@mrluanma  ，求助

**Comment by mrluanma** [comment]
OpenShift 已侧地沦陷。

**Comment by instafun** [comment]
Shit...Heroku还行，不过文件下载经常断，有解决都办法吗？

**Comment by mrluanma** [comment]
OpenShift 被滥用的更严重，一直都没有 Heroku 靠谱。

非技术问题我不希望在公开场合讨论，有兴趣的话可以给我发邮件。邮件地址见我 GitHub Profile 页面。

**Comment by mrluanma** [comment]
@instafun 之前是我造成了一个衰退，在 0d1a7de2c6e162 里修复了。
