### ISSUE TITLE
OpenShift部署后无法连接，错误提示见内文

### ISSUE THREAD

**Issue by catdog** [mrluanma/shadowsocks-heroku#7]
用的是自己绑的域名，用浏览器可以正常访问（内容是“asdf."），
客户端出现如下提示“remote www.google.com:443 error: Error: Hostname/IP doesn't match certificate's altnames”
请问一下是哪里出了问题，谢谢

**Comment by ohyeah521** [comment]
换个网址试试

**Comment by catdog** [comment]
另外还有俩问题请教：

1.有没有办法可以改server端的port number呢？
2.目前除了rc4还支持什么加密方式?和原生ShadowSocks的加密方式都一样么？

**Comment by mrluanma** [comment]
@catdog 

```
$ node local.js -m rc4 -k foobar -s 'wss://asdfasdf-qwert.rhcloud.com:8443'
```

请把 wss 更换成 ws，8443 更换成 8000 再试一下。

`remote www.google.com:443 error: Error: Hostname/IP doesn't match certificate's altnames` 这个看起来是在建立 WebSocket 连接的时候证书验证失败，OpenShift 提供的证书只对 *.rhcloud.com 有效。

你方便的话邮件把你绑定域名的域名 **私下邮件** 告诉我一下，我验证并修复一下。

1、server 端的端口是平台规定的，不能更换。
2、应该支持下列的加密方式：

```
aes-256-cfb
aes-128-cfb
aes-192-cfb
aes-256-ofb
aes-128-ofb
aes-192-ofb
aes-128-ctr
aes-192-ctr
aes-256-ctr
aes-128-cfb8
aes-192-cfb8
aes-256-cfb8
aes-128-cfb1
aes-192-cfb1
aes-256-cfb1
table
rc4
null
```

null 不做任何加密，用于在 WebSocket 连接已经是 wss 的情况。

**Comment by mrluanma** [comment]
用 `NODE_TLS_REJECT_UNAUTHORIZED=0` 关掉验证之后会出现另外的错误：

```
$ NODE_TLS_REJECT_UNAUTHORIZED=0 node local.js -s 'wss://xxx.xxx.xxx:8443' -k xxxxx -m rc4
server listening at { address: '127.0.0.1', family: 'IPv4', port: 1080 }
local connected
concurrent connections: 1
remote 54.175.219.8:80 error: server responded with an invalid protocol
concurrent connections: 0
```

这说明 OpenShift 的 WebSocket 端口（8000、8443）用自定义域名一样无法访问了，奇怪的是 HTTP 和 HTTPS 居然是好的。

已经在墙外的 VPS 验证过，代码没有问题。

**Comment by mrluanma** [comment]
如果使用自定义域名设置需要 `NODE_TLS_REJECT_UNAUTHORIZED` 环境变量为 `0` 关闭证书验证。不过最好不使用自定义域名，一是没必要，而是证书验证很重要，如果证书可信，那可以使用 `null` 加密方式不再 **再次** 加密。

```
NODE_TLS_REJECT_UNAUTHORIZED=0 node local.js -m rc4 -k foobar -s 'wss://xxxx.xxxx.com:8443'
```
