### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by ohyeah521** [mrluanma/shadowsocks-heroku#8]
concurrent connections: 14
local disconnected
concurrent connections: 13
local disconnected
concurrent connections: 12
local disconnected
concurrent connections: 11

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at TCP.onread (net.js:559:19)

我昨天更新的代码。

**Comment by catdog** [comment]
遇到同样的出错信息

**Comment by mrluanma** [comment]
@ohyeah521 @catdog 

请提供更多的信息。操作系统版本，Node 版本，哪个平台，是否已经把代码更新到最新？使用的哪种加密方式？我这里不能重现。

**Comment by catdog** [comment]
Windows x64 8.1 
node v0.10.35
m=rc4

**Comment by ohyeah521** [comment]
win7 sp1 x32 
node-v0.10.35-x86
m=rc4
代码是最新的

**Comment by JoeWoo** [comment]
我这里遇到同样的问题：MAC OS X 10.10 ; node v0.10.35 ; m=rc4 运行一会儿后自己出错退出。

**Comment by mrluanma** [comment]
@ohyeah521 @catdog @JoeWoo 

请告知一下使用的是那个平台（Heroku/OpenShift?)，是 ws 还是 wss 协议？

**Comment by ohyeah521** [comment]
heroku 平台

command:
node local.js -s    mydomain.com   -l 8140 -m rc4 -k keyword -r 80

**Comment by mrluanma** [comment]
@ohyeah521 @catdog @JoeWoo 

请试试最新的代码，我测试下来没问题了。

**Comment by JoeWoo** [comment]
@mrluanma  heroku ws 协议。我遇到的error是超时。更新了代码问题还是复现。
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ETIMEDOUT
    at errnoException (net.js:905:11)
    at TCP.onread (net.js:559:19)
```
下面link给你参考：
http://stackoverflow.com/questions/14972106/how-to-deal-with-read-etimedout-in-node-js
