### ISSUE TITLE
works very well, but not for all website?

### ISSUE THREAD

**Issue by nodje** [mrluanma/shadowsocks-heroku#9]
Hey,

very nice job, got it working very quickly! Many thanks!
It's pretty fast, stable as far as I can tell.

Now I want to try to put the client on a router ;)

But oddly, it doesn't seem to work for some website.
ex: for http://www.geoiptool.com/ I get a connection reset
No error in the console though.

Do you think it could be due to the WSS protocol ?

**Comment by mrluanma** [comment]
No.

It seems those website has DNS issue on Heroku/OpenShift.

Heroku:

```
$ heroku run bash
Running `bash` attached to terminal... up, run.9791
~ $ curl -v http://www.geoiptool.com/
* Hostname was NOT found in DNS cache
* Could not resolve host: www.geoiptool.com
* Closing connection 0
curl: (6) Could not resolve host: www.geoiptool.com
```

**Comment by mrluanma** [comment]
Heroku can NOT reach the DNS server of www.geoiptool.com domain:

```
~ $ dig www.geoiptool.com

; <<>> DiG 9.9.5-3ubuntu0.1-Ubuntu <<>> www.geoiptool.com
;; global options: +cmd
;; connection timed out; no servers could be reached
```

It can resolve successfully using Google Public DNS servers:

```
~ $ dig www.geoiptool.com @8.8.8.8

; <<>> DiG 9.9.5-3ubuntu0.1-Ubuntu <<>> www.geoiptool.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41687
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.geoiptool.com.		IN	A

;; ANSWER SECTION:
www.geoiptool.com.	302	IN	A	198.100.155.19

;; Query time: 13 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Jan 26 07:01:09 UTC 2015
;; MSG SIZE  rcvd: 62
```

**Comment by nodje** [comment]
I'm using Openshift actually, but ok, it's weird but make sense, it's not an issue with WSS protocol in any case.
